version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/back_end/saolei"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/front_end"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
