version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/back_end/saolei"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/front_end"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@primeuix/themes"
        versions: [">= 3.0.0"]
      - dependency-name: "primeicons"
        versions: [">= 8.0.0"]
      - dependency-name: "primevue"
        versions: [">= 5.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
