# Generated by Django 4.2.4 on 2023-08-28 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msuser", "0001_initial"),
        ("userprofile", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="bio",
            new_name="signature",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="userms",
            field=models.OneToOneField(
                default=666,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="msuser.userms",
            ),
            preserve_default=False,
        ),
    ]
