# Generated by Django 4.2.4 on 2023-10-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_userprofile_userms"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
