# Generated by Django 4.2.4 on 2023-08-29 19:32

from django.db import migrations
import userprofile.fields


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=userprofile.fields.RestrictedImageField(
                blank=True, null=True, upload_to="assets/avatar/%Y%m%d/"
            ),
        ),
    ]
