from django.db import models
# from userprofile.models import UserProfile

def get_default_designators():
    return []

# 扫雷用户
class UserMS(models.Model):
    # 用户的标识。管理员审核通过后可以自由使用该标识。
    designators = models.JSONField(default=get_default_designators)
    # 总录像数限制默认100，计划管理员可以修改。高水平玩家也可以增多。
    # 高级标准sub100是200；sub60是500；sub50是600；sub40是800；sub30是1000；vip是1000。
    video_num_limit = models.IntegerField(null=False, default=100)
    # 录像总数
    video_num_total = models.IntegerField(null=False, default=0)
    # 初级录像数
    video_num_beg = models.IntegerField(null=False, default=0)
    # 中级录像数
    video_num_int = models.IntegerField(null=False, default=0)
    # 高级录像数
    video_num_exp = models.IntegerField(null=False, default=0)
    # 标准录像数
    video_num_std = models.IntegerField(null=False, default=0)
    # 盲扫录像数
    video_num_nf = models.IntegerField(null=False, default=0)
    # 竞速无猜录像数
    video_num_ng = models.IntegerField(null=False, default=0)
    # 递归录像数
    video_num_dg = models.IntegerField(null=False, default=0)

    # 标准、盲扫、竞速无猜、递归的记录
    b_time_std = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    b_time_id_std = models.BigIntegerField(null=True)
    i_time_std = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    i_time_id_std = models.BigIntegerField(null=True)
    e_time_std = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    e_time_id_std = models.BigIntegerField(null=True)
    b_bvs_std = models.FloatField(default=0.0)
    b_bvs_id_std = models.BigIntegerField(null=True)
    i_bvs_std = models.FloatField(default=0.0)
    i_bvs_id_std = models.BigIntegerField(null=True)
    e_bvs_std = models.FloatField(default=0.0)
    e_bvs_id_std = models.BigIntegerField(null=True)
    b_stnb_std = models.FloatField(default=0.0)
    b_stnb_id_std = models.BigIntegerField(null=True)
    i_stnb_std = models.FloatField(default=0.0)
    i_stnb_id_std = models.BigIntegerField(null=True)
    e_stnb_std = models.FloatField(default=0.0)
    e_stnb_id_std = models.BigIntegerField(null=True)
    b_ioe_std = models.FloatField(default=0.0)
    b_ioe_id_std = models.BigIntegerField(null=True)
    i_ioe_std = models.FloatField(default=0.0)
    i_ioe_id_std = models.BigIntegerField(null=True)
    e_ioe_std = models.FloatField(default=0.0)
    e_ioe_id_std = models.BigIntegerField(null=True)
    b_path_std = models.FloatField(default=99999.9)
    b_path_id_std = models.BigIntegerField(null=True)
    i_path_std = models.FloatField(default=99999.9)
    i_path_id_std = models.BigIntegerField(null=True)
    e_path_std = models.FloatField(default=99999.9)
    e_path_id_std = models.BigIntegerField(null=True)

    b_time_nf = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    b_time_id_nf = models.BigIntegerField(null=True)
    i_time_nf = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    i_time_id_nf = models.BigIntegerField(null=True)
    e_time_nf = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    e_time_id_nf = models.BigIntegerField(null=True)
    b_bvs_nf = models.FloatField(default=0.0)
    b_bvs_id_nf = models.BigIntegerField(null=True)
    i_bvs_nf = models.FloatField(default=0.0)
    i_bvs_id_nf = models.BigIntegerField(null=True)
    e_bvs_nf = models.FloatField(default=0.0)
    e_bvs_id_nf = models.BigIntegerField(null=True)
    b_stnb_nf = models.FloatField(default=0.0)
    b_stnb_id_nf = models.BigIntegerField(null=True)
    i_stnb_nf = models.FloatField(default=0.0)
    i_stnb_id_nf = models.BigIntegerField(null=True)
    e_stnb_nf = models.FloatField(default=0.0)
    e_stnb_id_nf = models.BigIntegerField(null=True)
    b_ioe_nf = models.FloatField(default=0.0)
    b_ioe_id_nf = models.BigIntegerField(null=True)
    i_ioe_nf = models.FloatField(default=0.0)
    i_ioe_id_nf = models.BigIntegerField(null=True)
    e_ioe_nf = models.FloatField(default=0.0)
    e_ioe_id_nf = models.BigIntegerField(null=True)
    b_path_nf = models.FloatField(default=99999.9)
    b_path_id_nf = models.BigIntegerField(null=True)
    i_path_nf = models.FloatField(default=99999.9)
    i_path_id_nf = models.BigIntegerField(null=True)
    e_path_nf = models.FloatField(default=99999.9)
    e_path_id_nf = models.BigIntegerField(null=True)

    b_time_ng = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    b_time_id_ng = models.BigIntegerField(null=True)
    i_time_ng = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    i_time_id_ng = models.BigIntegerField(null=True)
    e_time_ng = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    e_time_id_ng = models.BigIntegerField(null=True)
    b_bvs_ng = models.FloatField(default=0.0)
    b_bvs_id_ng = models.BigIntegerField(null=True)
    i_bvs_ng = models.FloatField(default=0.0)
    i_bvs_id_ng = models.BigIntegerField(null=True)
    e_bvs_ng = models.FloatField(default=0.0)
    e_bvs_id_ng = models.BigIntegerField(null=True)
    b_stnb_ng = models.FloatField(default=0.0)
    b_stnb_id_ng = models.BigIntegerField(null=True)
    i_stnb_ng = models.FloatField(default=0.0)
    i_stnb_id_ng = models.BigIntegerField(null=True)
    e_stnb_ng = models.FloatField(default=0.0)
    e_stnb_id_ng = models.BigIntegerField(null=True)
    b_ioe_ng = models.FloatField(default=0.0)
    b_ioe_id_ng = models.BigIntegerField(null=True)
    i_ioe_ng = models.FloatField(default=0.0)
    i_ioe_id_ng = models.BigIntegerField(null=True)
    e_ioe_ng = models.FloatField(default=0.0)
    e_ioe_id_ng = models.BigIntegerField(null=True)
    b_path_ng = models.FloatField(default=99999.9)
    b_path_id_ng = models.BigIntegerField(null=True)
    i_path_ng = models.FloatField(default=99999.9)
    i_path_id_ng = models.BigIntegerField(null=True)
    e_path_ng = models.FloatField(default=99999.9)
    e_path_id_ng = models.BigIntegerField(null=True)

    b_time_dg = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    b_time_id_dg = models.BigIntegerField(null=True)
    i_time_dg = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    i_time_id_dg = models.BigIntegerField(null=True)
    e_time_dg = models.DecimalField(max_digits=6, decimal_places=3, default=999.999)
    e_time_id_dg = models.BigIntegerField(null=True)
    b_bvs_dg = models.FloatField(default=0.0)
    b_bvs_id_dg = models.BigIntegerField(null=True)
    i_bvs_dg = models.FloatField(default=0.0)
    i_bvs_id_dg = models.BigIntegerField(null=True)
    e_bvs_dg = models.FloatField(default=0.0)
    e_bvs_id_dg = models.BigIntegerField(null=True)
    b_stnb_dg = models.FloatField(default=0.0)
    b_stnb_id_dg = models.BigIntegerField(null=True)
    i_stnb_dg = models.FloatField(default=0.0)
    i_stnb_id_dg = models.BigIntegerField(null=True)
    e_stnb_dg = models.FloatField(default=0.0)
    e_stnb_id_dg = models.BigIntegerField(null=True)
    b_ioe_dg = models.FloatField(default=0.0)
    b_ioe_id_dg = models.BigIntegerField(null=True)
    i_ioe_dg = models.FloatField(default=0.0)
    i_ioe_id_dg = models.BigIntegerField(null=True)
    e_ioe_dg = models.FloatField(default=0.0)
    e_ioe_id_dg = models.BigIntegerField(null=True)
    b_path_dg = models.FloatField(default=99999.9)
    b_path_id_dg = models.BigIntegerField(null=True)
    i_path_dg = models.FloatField(default=99999.9)
    i_path_id_dg = models.BigIntegerField(null=True)
    e_path_dg = models.FloatField(default=99999.9)
    e_path_id_dg = models.BigIntegerField(null=True)

    def __str__(self):
        return 'designators: {}'.format(self.designators)
