use saolei;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS auth_group;
DROP TABLE IF EXISTS auth_group_permissions;
DROP TABLE IF EXISTS auth_permission;
DROP TABLE IF EXISTS captcha_captchastore;
DROP TABLE IF EXISTS django_admin_log;
DROP TABLE IF EXISTS django_apscheduler_djangojob;
DROP TABLE IF EXISTS django_apscheduler_djangojobexecution;
DROP TABLE IF EXISTS django_content_type;
DROP TABLE IF EXISTS django_migrations;
DROP TABLE IF EXISTS django_session;
DROP TABLE IF EXISTS msuser_userms;
DROP TABLE IF EXISTS userprofile_emailverifyrecord;
DROP TABLE IF EXISTS userprofile_userprofile;
DROP TABLE IF EXISTS userprofile_userprofile_groups;
DROP TABLE IF EXISTS userprofile_userprofile_user_permissions;
DROP TABLE IF EXISTS videomanager_videomodel;
DROP TABLE IF EXISTS videomanager_expandvideomodel;
DROP TABLE IF EXISTS ranking_match;
DROP TABLE IF EXISTS ranking_usermsscorerank;
DROP TABLE IF EXISTS identifier_identifier;
SET FOREIGN_KEY_CHECKS=1;
