# Generated by Django 4.2.4 on 2023-10-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "b_time_std",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("b_time_id_std", models.BigIntegerField(null=True)),
                (
                    "i_time_std",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("i_time_id_std", models.BigIntegerField(null=True)),
                (
                    "e_time_std",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("e_time_id_std", models.BigIntegerField(null=True)),
                ("b_bvs_std", models.FloatField(default=0.0)),
                ("b_bvs_id_std", models.BigIntegerField(null=True)),
                ("i_bvs_std", models.FloatField(default=0.0)),
                ("i_bvs_id_std", models.BigIntegerField(null=True)),
                ("e_bvs_std", models.FloatField(default=0.0)),
                ("e_bvs_id_std", models.BigIntegerField(null=True)),
                ("b_stnb_std", models.FloatField(default=0.0)),
                ("b_stnb_id_std", models.BigIntegerField(null=True)),
                ("i_stnb_std", models.FloatField(default=0.0)),
                ("i_stnb_id_std", models.BigIntegerField(null=True)),
                ("e_stnb_std", models.FloatField(default=0.0)),
                ("e_stnb_id_std", models.BigIntegerField(null=True)),
                ("b_ioe_std", models.FloatField(default=0.0)),
                ("b_ioe_id_std", models.BigIntegerField(null=True)),
                ("i_ioe_std", models.FloatField(default=0.0)),
                ("i_ioe_id_std", models.BigIntegerField(null=True)),
                ("e_ioe_std", models.FloatField(default=0.0)),
                ("e_ioe_id_std", models.BigIntegerField(null=True)),
                ("b_path_std", models.FloatField(default=99999.9)),
                ("b_path_id_std", models.BigIntegerField(null=True)),
                ("i_path_std", models.FloatField(default=99999.9)),
                ("i_path_id_std", models.BigIntegerField(null=True)),
                ("e_path_std", models.FloatField(default=99999.9)),
                ("e_path_id_std", models.BigIntegerField(null=True)),
                (
                    "b_time_nf",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("b_time_id_nf", models.BigIntegerField(null=True)),
                (
                    "i_time_nf",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("i_time_id_nf", models.BigIntegerField(null=True)),
                (
                    "e_time_nf",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("e_time_id_nf", models.BigIntegerField(null=True)),
                ("b_bvs_nf", models.FloatField(default=0.0)),
                ("b_bvs_id_nf", models.BigIntegerField(null=True)),
                ("i_bvs_nf", models.FloatField(default=0.0)),
                ("i_bvs_id_nf", models.BigIntegerField(null=True)),
                ("e_bvs_nf", models.FloatField(default=0.0)),
                ("e_bvs_id_nf", models.BigIntegerField(null=True)),
                ("b_stnb_nf", models.FloatField(default=0.0)),
                ("b_stnb_id_nf", models.BigIntegerField(null=True)),
                ("i_stnb_nf", models.FloatField(default=0.0)),
                ("i_stnb_id_nf", models.BigIntegerField(null=True)),
                ("e_stnb_nf", models.FloatField(default=0.0)),
                ("e_stnb_id_nf", models.BigIntegerField(null=True)),
                ("b_ioe_nf", models.FloatField(default=0.0)),
                ("b_ioe_id_nf", models.BigIntegerField(null=True)),
                ("i_ioe_nf", models.FloatField(default=0.0)),
                ("i_ioe_id_nf", models.BigIntegerField(null=True)),
                ("e_ioe_nf", models.FloatField(default=0.0)),
                ("e_ioe_id_nf", models.BigIntegerField(null=True)),
                ("b_path_nf", models.FloatField(default=99999.9)),
                ("b_path_id_nf", models.BigIntegerField(null=True)),
                ("i_path_nf", models.FloatField(default=99999.9)),
                ("i_path_id_nf", models.BigIntegerField(null=True)),
                ("e_path_nf", models.FloatField(default=99999.9)),
                ("e_path_id_nf", models.BigIntegerField(null=True)),
                (
                    "b_time_ng",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("b_time_id_ng", models.BigIntegerField(null=True)),
                (
                    "i_time_ng",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("i_time_id_ng", models.BigIntegerField(null=True)),
                (
                    "e_time_ng",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("e_time_id_ng", models.BigIntegerField(null=True)),
                ("b_bvs_ng", models.FloatField(default=0.0)),
                ("b_bvs_id_ng", models.BigIntegerField(null=True)),
                ("i_bvs_ng", models.FloatField(default=0.0)),
                ("i_bvs_id_ng", models.BigIntegerField(null=True)),
                ("e_bvs_ng", models.FloatField(default=0.0)),
                ("e_bvs_id_ng", models.BigIntegerField(null=True)),
                ("b_stnb_ng", models.FloatField(default=0.0)),
                ("b_stnb_id_ng", models.BigIntegerField(null=True)),
                ("i_stnb_ng", models.FloatField(default=0.0)),
                ("i_stnb_id_ng", models.BigIntegerField(null=True)),
                ("e_stnb_ng", models.FloatField(default=0.0)),
                ("e_stnb_id_ng", models.BigIntegerField(null=True)),
                ("b_ioe_ng", models.FloatField(default=0.0)),
                ("b_ioe_id_ng", models.BigIntegerField(null=True)),
                ("i_ioe_ng", models.FloatField(default=0.0)),
                ("i_ioe_id_ng", models.BigIntegerField(null=True)),
                ("e_ioe_ng", models.FloatField(default=0.0)),
                ("e_ioe_id_ng", models.BigIntegerField(null=True)),
                ("b_path_ng", models.FloatField(default=99999.9)),
                ("b_path_id_ng", models.BigIntegerField(null=True)),
                ("i_path_ng", models.FloatField(default=99999.9)),
                ("i_path_id_ng", models.BigIntegerField(null=True)),
                ("e_path_ng", models.FloatField(default=99999.9)),
                ("e_path_id_ng", models.BigIntegerField(null=True)),
                (
                    "b_time_dg",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("b_time_id_dg", models.BigIntegerField(null=True)),
                (
                    "i_time_dg",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("i_time_id_dg", models.BigIntegerField(null=True)),
                (
                    "e_time_dg",
                    models.DecimalField(
                        decimal_places=3, default=999.999, max_digits=6
                    ),
                ),
                ("e_time_id_dg", models.BigIntegerField(null=True)),
                ("b_bvs_dg", models.FloatField(default=0.0)),
                ("b_bvs_id_dg", models.BigIntegerField(null=True)),
                ("i_bvs_dg", models.FloatField(default=0.0)),
                ("i_bvs_id_dg", models.BigIntegerField(null=True)),
                ("e_bvs_dg", models.FloatField(default=0.0)),
                ("e_bvs_id_dg", models.BigIntegerField(null=True)),
                ("b_stnb_dg", models.FloatField(default=0.0)),
                ("b_stnb_id_dg", models.BigIntegerField(null=True)),
                ("i_stnb_dg", models.FloatField(default=0.0)),
                ("i_stnb_id_dg", models.BigIntegerField(null=True)),
                ("e_stnb_dg", models.FloatField(default=0.0)),
                ("e_stnb_id_dg", models.BigIntegerField(null=True)),
                ("b_ioe_dg", models.FloatField(default=0.0)),
                ("b_ioe_id_dg", models.BigIntegerField(null=True)),
                ("i_ioe_dg", models.FloatField(default=0.0)),
                ("i_ioe_id_dg", models.BigIntegerField(null=True)),
                ("e_ioe_dg", models.FloatField(default=0.0)),
                ("e_ioe_id_dg", models.BigIntegerField(null=True)),
                ("b_path_dg", models.FloatField(default=99999.9)),
                ("b_path_id_dg", models.BigIntegerField(null=True)),
                ("i_path_dg", models.FloatField(default=99999.9)),
                ("i_path_id_dg", models.BigIntegerField(null=True)),
                ("e_path_dg", models.FloatField(default=99999.9)),
                ("e_path_id_dg", models.BigIntegerField(null=True)),
            ],
        ),
    ]
