name: Back-end Test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    paths: 
      - 'back_end/saolei/**'
      - '.github/workflows/backend.yml'
      - '.github/workflows/codecov.yml'

jobs:
  check_flag:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back_end/saolei

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: saolei
          MYSQL_ROOT_PASSWORD: 123456
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
      redis:  # 添加 Redis 服务
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Choose the Python version you want to use

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install cryptography
        pip install coverage pytest-cov

    - name: Create Logs Directory
      run: mkdir -p logs

    - name: Run Tests
      run: |
        python manage.py makemigrations
        python manage.py migrate
        coverage run manage.py test
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
