name: Cypress Tests

on:
  pull_request:
    paths: 
      - 'front_end/**'
      - '.github/workflows/cypress.yml'

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: front_end
    strategy:
      matrix:
        browser: [chrome, firefox, edge, electron, chrome-109]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      - name: Install dependencies
        run: npm install

      # Install Chrome 109 only for that matrix entry
      - name: Install Chrome 109
        if: matrix.browser == 'chrome-109'
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_109.0.5414.74-1_amd64.deb
          sudo dpkg -i google-chrome-stable_109.0.5414.74-1_amd64.deb || sudo apt-get -fy install

      - name: Check browser version
        run: |
          if [[ "${{ matrix.browser }}" == "chrome-109" || "${{ matrix.browser }}" == "chrome" ]]; then
            google-chrome --version
          elif [[ "${{ matrix.browser }}" == "firefox" ]]; then
            firefox --version
          fi
        shell: bash

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          start: npm run dev
          working-directory: front_end
          browser: ${{ matrix.browser == 'chrome-109' && 'chrome' || matrix.browser }}
        env:
          CYPRESS_INSTALL_BINARY: 0
