name: Cypress Tests

on:
  pull_request:
    paths: 
      - 'front_end/**'
      - '.github/workflows/cypress.yml'

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: front_end
    strategy:
      matrix:
        browser: [chrome, firefox, edge, electron]
        image: [latest, node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1]
    container:
      image: cypress/included:${{ matrix.image }}
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      - name: Install dependencies
        run: npm install
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          start: npm run dev
          working-directory: front_end
          browser: ${{ matrix.browser }}
