name: Cypress Tests

on:
  pull_request:
    paths: 
      - 'front_end/**'
      - '.github/workflows/cypress.yml'

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: front_end
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      - name: Install dependencies
        run: npm install
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
