name: Cypress Tests

on:
  pull_request:
    paths: 
      - 'front_end/**'
      - '.github/workflows/cypress.yml'

jobs:
  cypress-run:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: front_end
    strategy:
      matrix:
        browser: [chrome, firefox, edge, electron, chrome-109]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      - name: Install dependencies
        run: npm install

      # Install Chrome 109 only for that matrix entry
      - name: Install Chrome 109
        if: matrix.browser == 'chrome-109'
        run: |
          choco uninstall googlechrome -y || echo "Chrome not installed"
          Invoke-WebRequest https://archive.org/download/chrome109offline64bit/Chrome109StandaloneSetup64.exe -OutFile chrome_installer.exe
          Start-Process chrome_installer.exe -Wait
          & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          start: npm run dev
          working-directory: front_end
          browser: ${{ matrix.browser == 'chrome-109' && 'chrome' || matrix.browser }}
