name: Front-end Code Style Check

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    paths: 
      - 'front_end/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front_end
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run lint